### PR TITLE
Smashing Magazine project completed

### PR DESCRIPTION
**Pull request by SafaErden**
Smashing Magazin structure replica for completing the "PROJECT: DESIGN TEARDOWN" section has been completed.

### CODE REVIEW

**Comment by sumancrest0001** [comment]
### STATUS: CHANGES REQUIRED

Hello TEAM :wave:  You guys have created a beautiful layout of the original site and added extra things than need which is very good. It is nearly a perfect project but there are some minor issues that need to be fixed to get :+1: :+1:  from our side.
Please make the following changes.

[REQUIRED] the first row of the article section should contain two articles but in your project, it's three. Have a look.
Screenshot from 2020-04-08 16-26-49

Original project :point_down: :point_down: 
Screenshot from 2020-04-08 16-34-56

**Comment by sumancrest0001** [comment]
[REQUIRED] We have to work on list-items of the footer section. One list item should not be divided into two lines. For example, E-commerce is divided into two lines. Please fix this issue.
**in your project.**
Screenshot from 2020-04-08 16-26-29

in the original project
Screenshot from 2020-04-08 16-39-02

**Comment by sumancrest0001** [comment]
These are optional changes and you can make changes if you want. (Nice to have) :slightly_smiling_face: 

[OPTIONAL] You can align the membership item of the top navbar on the same line as that of other items so it looks like a navbar of the original site.
Screenshot from 2020-04-08 16-27-03

in the original site.
Screenshot from 2020-04-08 16-43-37

**Comment by sumancrest0001** [comment]
Kindly make the above changes and submit the project for another review. I am confident that it won't take that long to make these changes. 
**All the best :+1: :+1:** 
You can message me on slack **(Suman Shrestha)** if you need help.

**Comment by lekegitrepo** [comment]
### Hi @SafaErden and @evansinho 🥇 ⭐️ 
### Excellent implementation. 👍  for implementing the requirements from the previous review.
### This project is approved.

### Reviewed by _Temitayo Adeleke_

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved

**Pull request merged**
